language: node_js
node_js:
- '8'
script:
  - npm test
before_deploy:
  - npm run deploy
deploy:
  provider: gh-pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: build
