language: node_js
node_js:
- '8'
script:
  - npm test
  - git remote set-branches --add origin master
  - git fetch
  - echo Linting the following JS files in this branch - `git diff --name-only origin/master -- '*.js'`
  - ./node_modules/eslint/bin/eslint.js --max-warnings 0 `git diff --name-only origin/master -- '*.js'`
